CREATE TABLE [dbo].[just_giving_pages] (
    [fundraiser_user_id]                                INT           NULL,
    [fundraiser_title]                                  VARCHAR (255) NULL,
    [fundraiser_first_name]                             VARCHAR (255) NULL,
    [fundraiser_last_name]                              VARCHAR (255) NULL,
    [fundraiser_address_line_1]                         VARCHAR (255) NULL,
    [fundraiser_address_line_2]                         VARCHAR (255) NULL,
    [fundraiser_town]                                   VARCHAR (255) NULL,
    [fundraiser_region]                                 VARCHAR (255) NULL,
    [fundraiser_postcode]                               VARCHAR (255) NULL,
    [fundraiser_country]                                VARCHAR (255) NULL,
    [fundraiser_email]                                  VARCHAR (255) NULL,
    [fundraiser_connected_benefit]                      VARCHAR (255) NULL,
    [fundraiser_further_contact]                        VARCHAR (255) NULL,
    [page_created_date]                                 DATE          NULL,
    [page_expiry_date]                                  DATE          NULL,
    [fundraiser_page_id]                                INT           NOT NULL,
    [fundraiser_page_title]                             VARCHAR (255) NULL,
    [offline_amount]                                    MONEY         NULL,
    [target_amount]                                     MONEY         NULL,
    [fundraiser_page_status]                            VARCHAR (255) NULL,
    [fundraiser_page_url]                               VARCHAR (255) NULL,
    [referral_site]                                     VARCHAR (255) NULL,
    [referral_site_url]                                 VARCHAR (255) NULL,
    [is_api_created]                                    BIT           NULL,
    [fundraiser_team_members]                           VARCHAR (255) NULL,
    [fundraiser_team]                                   VARCHAR (512) NULL,
    [fundraiser_team_url]                               VARCHAR (255) NULL,
    [organisation_portal]                               VARCHAR (255) NULL,
    [organisation_portal_url]                           VARCHAR (255) NULL,
    [in_memoriam]                                       BIT           NULL,
    [in_memoriam_name]                                  VARCHAR (255) NULL,
    [in_memoriam_first_name]                            VARCHAR (255) NULL,
    [in_memoriam_last_name]                             VARCHAR (255) NULL,
    [in_memoriam_town]                                  VARCHAR (255) NULL,
    [in_memoriam_gender]                                VARCHAR (255) NULL,
    [in_memoriam_date_of_birth]                         DATE          NULL,
    [in_memoriam_date_of_death]                         DATE          NULL,
    [in_memoriam_relationship]                          VARCHAR (255) NULL,
    [birthday_name]                                     VARCHAR (255) NULL,
    [wedding_names]                                     VARCHAR (255) NULL,
    [event_name]                                        VARCHAR (255) NULL,
    [event_id]                                          INT           NULL,
    [promoted_event]                                    BIT           NULL,
    [event_category]                                    VARCHAR (255) NULL,
    [overseas_event]                                    BIT           NULL,
    [user_created_event]                                BIT           NULL,
    [event_date]                                        DATE          NULL,
    [event_expiry_date]                                 DATE          NULL,
    [appeal_name]                                       VARCHAR (255) NULL,
    [number_sms_donations]                              INT           NULL,
    [total_sms_donations]                               INT           NULL,
    [number_online_donations]                           INT           NULL,
    [total_donations]                                   MONEY         NULL,
    [total_donations_plus_gift_aid]                     MONEY         NULL,
    [total_donations_and_gift_aid_minus_estimated_fees] MONEY         NULL,
    [event_custom_code_1]                               VARCHAR (255) NULL,
    [event_custom_code_2]                               VARCHAR (255) NULL,
    [event_custom_code_3]                               VARCHAR (255) NULL,
    [page_custom_code_1]                                VARCHAR (255) NULL,
    [page_custom_code_2]                                VARCHAR (255) NULL,
    [page_custom_code_3]                                VARCHAR (255) NULL,
    [page_custom_code_4]                                VARCHAR (255) NULL,
    [page_custom_code_5]                                VARCHAR (255) NULL,
    [page_custom_code_6]                                VARCHAR (255) NULL,
    [custom_campaign_code_1]                            VARCHAR (255) NULL,
    [custom_campaign_code_2]                            VARCHAR (255) NULL,
    [custom_campaign_code_3]                            VARCHAR (255) NULL,
    [fundraiser_page_consent]                           BIT           NULL,
    [fundraiser_page_consent_date]                      DATETIME      NULL,
    [fundraiser_page_privacy_notice_version]            VARCHAR (255) NULL,
    [fundraiser_page_consent_statement]                 VARCHAR (255) NULL,
    [fundraising_page_team_id]                          VARCHAR (255) NULL,
    [fundraising_page_team_member_role]                 VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([fundraiser_page_id] ASC)
);

